permalink: /:year/:month/:day/:title.html
paginate: 10
highlighter: rouge
# markdown: redcarpet
markdown: kramdown
#kramdown:
   #input: GFM
   #hard_wrap: false

# 作者信息
author:
  name: Yi Ting
  email: chengyi818@foxmail.com
  link:
  weibo: http://weibo.com/5799947471/profile?topnav=1&wvr=6
  github: http://github.com/chengyi818
  linkedin: https://cn.linkedin.com/in/祎-成-060941111
  facebook: https://www.facebook.com/profile.php?id=100010920649089

# 站点信息
name: 一亭
title: 祎婷之家
description: 夜阑卧听风吹雨，铁马冰河入梦来
url: http://chengyi818.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/ring.gif
favicon: /public/img/love.jpg

# google analytics 设置
ga:
  id: UA-72539373-1
  url: yiting.co

# disqus 设置
disqus:
  shortname: chengyi818

# 主题设置，自动激活某个标签
active: 侣行

# 首页除了最新文章外显示分类
tags_display:
  - 深度

locals:
  index: 主页
  tags: 标签
  about: 我们
  newest: 最新文章
  archive: 归档

#增加了对emoji表情的支持
gems:
  - jemoji
