permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
highlighter: pygments

# 作者信息
author:
  name: Yi Ting
  email: chengyi818@foxmail.com
  link:
  weibo:
  github: http://github.com/chengyi818
  music:
  linkedin: https://www.linkedin.com/home?trk=nav_responsive_tab_home

# 站点信息
name: 一亭
title: 祎婷的博客
description: 夜阑卧听风吹雨，铁马冰河入梦来
url: http://chengyi818.github.io
rss_url:

# gavatar头像及Favicon
gavatar: /public/img/banzhuan01.jpg
favicon: /public/img/banzhuan01.jpg

# google analytics 设置
ga:
  id:
  url: http://chengyi818.github.io

# disqus 设置
disqus:
  shortname: chengyi818

# 主题设置，自动激活某个标签
active: 侣行

# 首页除了最新文章外显示分类
cates:
  - openwrt

locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
